### ISSUE TITLE
Adding a way to update existing items when the user tries to add it as new.

### ISSUE THREAD

**Issue by OctoPie559** [Erick559/inventory-management#1]
My Simple inventory system is able to add, update and view items in a database. The language used is Python and sqlite3. I would want to find a way to update an existing item if a user tries to add it as an new item.

**Comment by NotNullBool** [comment]
So you want to add a check into your add item method for item id? if item i.d. is equal then change the name and quantity?

**Comment by OctoPie559** [comment]
Yes that's right. Currently when i add an already existing item i get an error. But what you said is what i exactly want

**Comment by NotNullBool** [comment]
ill make a pr shortly :)
